In [8]:
import numpy as np
import keras.backend as K

Using TensorFlow backend.
/Users/shenshen/Veril/ENV/lib/python3.7/site-packages/tensorflow-1.14.0-py3.7-macosx-10.14-x86_64.egg/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shenshen/Veril/ENV/lib/python3.7/site-packages/tensorflow-1.14.0-py3.7-macosx-10.14-x86_64.egg/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shenshen/Veril/ENV/lib/python3.7/site-packages/tensorflow-1.14.0-py3.7-macosx-10.14-x86_64.egg/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it wil

In [22]:
AA =K.constant([[0, 0, 0], [0, 0, 0], [0, 0, 0], [
                    1, 0, 0], [0, 1, 0], [0, 0, 1], ], shape=(6, 3))

In [23]:
K.eval(AA)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [24]:
bb = K.reshape(K.variable(np.array([1,2,3,4,5,6])),(1,6))

In [25]:
K.eval(K.dot(bb,AA))

array([[4., 5., 6.]], dtype=float32)

In [26]:
aa=np.array([1,0,1])

In [28]:
np.nonzero(aa)

(array([0, 2]),)

In [33]:
x=np.reshape(np.array([1,2,3]),(1,3))

In [34]:
print(x.shape)

(1, 3)


In [41]:
print(x[0,np.nonzero(aa)].shape)

(1, 2)
